### ISSUE TITLE
\cn\GB2260::parse(130430) 报错

### ISSUE THREAD

**Issue by BigKuCha** [cn/GB2260.php#14]
只要是以一个0结尾的code，parse()都会抛出错误。

比如 130530 ， 130430

**Comment by lepture** [comment]
@BigKuCha please submit a PR to fix it.

**Comment by lichunqiang** [comment]
@BigKuCha U can upgrade to master branch

**Comment by gaomd** [comment]
@BigKuCha This bug was fixed in commit https://github.com/cn/GB2260.php/commit/af4386b048e7ffae20f55b53cfcf5738af8d05ba in 2016.

Please update your `composer.json` file to require `"cn/gb2260": "dev-master"`, then issue a `composer update`.

Also, note that the method signature was updated to follow spec v0.2, please update your codes accordingly.

---

这个 bug 已在 2016 年被修复（ commit https://github.com/cn/GB2260.php/commit/af4386b048e7ffae20f55b53cfcf5738af8d05ba ）

你需要将 `composer.json` 中的 require 部分更新为 `"cn/gb2260": "dev-master"`，然后执行
 `composer update`。

还需要注意的是方法名已根据 spec v0.2 进行重构，请对调用代码做相应更新。
