### ISSUE TITLE
Versioning 

### ISSUE THREAD

**Issue by lichunqiang** [cn/GB2260.php#8]
It should be followed the [semantic versioning 2.0.0](http://semver.org/)

**Comment by gaomd** [comment]
There are two approaches I can think of:
1. If the spec version is 0.3, then we name our package 0.3.0 ~ 0.3.9999, this way, we follow the spec and semantic versioning simultaneously, any better ideas?
2. The `thephpleague/commonmark` project is doing another approach, which maintains an [mapping table](https://github.com/thephpleague/commonmark#compatibility-with-commonmark) of package version to spec version.

Since in spec we defined interfaces specifically, I think it would be better for us to follow the 1st approach.

**Comment by lepture** [comment]
@gaomd the spec is a draft currently. It would be ok with any approach. When the spec goes to 1.0, we hope the versioning of implementations would be 1.x.x. The spec will be 1.0, 2.0, 3.0, spec itself will never be something like 1.1.

**Comment by gaomd** [comment]
Discussion moved https://github.com/cn/GB2260/issues/34
